# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=20000, verbose_name='Текст'),
        ),
    ]
