# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('utm_content', models.CharField(max_length=200, verbose_name='Ключевое слово, по которому было показано объявление')),
                ('utm_source', models.CharField(blank=True, help_text='search – поисковая площадка<br/>context – тематическая (РСЯ)', max_length=200, null=True, verbose_name='Источник')),
                ('utm_campaign', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя компании.')),
                ('utm_medium', models.CharField(max_length=200, verbose_name='Рекламная метка')),
            ],
            options={
                'verbose_name': 'UTM Метка',
                'verbose_name_plural': 'UTM Метки',
                'db_table': 'cosmeticsyou_advertising_utm_marks',
            },
        ),
    ]
