# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='utm_term',
            field=models.CharField(default=2, max_length=200, verbose_name='Тип трафика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='utm_campaign',
            field=models.CharField(max_length=200, verbose_name='Название рекламной кампании'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='utm_content',
            field=models.CharField(max_length=200, verbose_name='Дополнительная информация, которая помогает различать объявления;'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='utm_medium',
            field=models.CharField(max_length=200, verbose_name='Тип трафика'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='utm_source',
            field=models.CharField(max_length=200, verbose_name='Источник перехода'),
        ),
    ]
