# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170608_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag_1',
            field=models.CharField(blank=True, choices=[('HTML', 'HTML'), ('JS', 'Java Script'), ('CSS', 'Css'), ('REACT', 'React'), ('SASS', 'Sass'), ('REDUX', 'Redux'), ('AJAX', 'AJAX'), ('WEB', 'Web'), ('PY', 'Python'), ('Django', 'Django'), ('CP', 'Concepts')], max_length=6, null=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag_2',
            field=models.CharField(blank=True, choices=[('HTML', 'HTML'), ('JS', 'Java Script'), ('CSS', 'Css'), ('REACT', 'React'), ('SASS', 'Sass'), ('REDUX', 'Redux'), ('AJAX', 'AJAX'), ('WEB', 'Web'), ('PY', 'Python'), ('Django', 'Django'), ('CP', 'Concepts')], max_length=6, null=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag_3',
            field=models.CharField(blank=True, choices=[('HTML', 'HTML'), ('JS', 'Java Script'), ('CSS', 'Css'), ('REACT', 'React'), ('SASS', 'Sass'), ('REDUX', 'Redux'), ('AJAX', 'AJAX'), ('WEB', 'Web'), ('PY', 'Python'), ('Django', 'Django'), ('CP', 'Concepts')], max_length=6, null=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag_4',
            field=models.CharField(blank=True, choices=[('HTML', 'HTML'), ('JS', 'Java Script'), ('CSS', 'Css'), ('REACT', 'React'), ('SASS', 'Sass'), ('REDUX', 'Redux'), ('AJAX', 'AJAX'), ('WEB', 'Web'), ('PY', 'Python'), ('Django', 'Django'), ('CP', 'Concepts')], max_length=6, null=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag_5',
            field=models.CharField(blank=True, choices=[('HTML', 'HTML'), ('JS', 'Java Script'), ('CSS', 'Css'), ('REACT', 'React'), ('SASS', 'Sass'), ('REDUX', 'Redux'), ('AJAX', 'AJAX'), ('WEB', 'Web'), ('PY', 'Python'), ('Django', 'Django'), ('CP', 'Concepts')], max_length=6, null=True, verbose_name='Тэг'),
        ),
    ]
