# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170613_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='Теги', to='blog.Tag'),
        ),
    ]
