# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170805_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('articles', models.ManyToManyField(to='blog.Article', verbose_name='Статьи')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Архив',
            },
        ),
    ]
