# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 19:51
from __future__ import unicode_literals

import blog.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170927_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_changing_password', models.BooleanField(default=False, verbose_name='Изменить пароль?')),
                ('username', models.CharField(default=None, max_length=140, unique=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=190, unique=True, verbose_name='Email')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'blog_user',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(max_length=2048, verbose_name='Год')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.BlogUser', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'blog_comment',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='article',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='К примеру, "new-share-for_2018"', max_length=150, null=True, validators=[blog.validators.validate_slug_field], verbose_name='Ссылка на статью'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='contact',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='tag',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='year',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='year',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='user_comments', to='blog.Comment', verbose_name='Комментарии'),
        ),
    ]
