# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-23 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180620_2251'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('extra_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='applause',
            field=models.IntegerField(default=0, verbose_name='Количество аплодисментов'),
        ),
        migrations.AddField(
            model_name='comment',
            name='applause',
            field=models.IntegerField(default=0, verbose_name='Количество аплодисментов'),
        ),
    ]
