# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-23 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180623_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='ID'),
        ),
    ]
