# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-23 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comment_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='comments',
        ),
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='article_comments', to='blog.Comment', verbose_name='Комментарии'),
        ),
    ]
