# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-26 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='preview',
        ),
    ]
