# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_squashed_0008_auto_20171126_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_changing_password',
            field=models.BooleanField(default=False, verbose_name='Изменить пароль?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='words',
            field=models.ManyToManyField(blank=True, related_name='words', to='words.Word', verbose_name='Слова'),
        ),
    ]
