# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    replaces = [('words', '0001_initial'), ('words', '0002_user_username'), ('words', '0003_auto_20171124_1024'), ('words', '0004_user'), ('words', '0005_auto_20171125_0844'), ('words', '0006_user_quantity_words'), ('words', '0007_auto_20171125_1014'), ('words', '0008_auto_20171126_0957')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'db_table': 'words',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default=None, max_length=140, unique=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=190, unique=True, verbose_name='Email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрировался')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('words', models.ManyToManyField(blank=True, null=True, related_name='words', to='words.Word', verbose_name='Слова')),
                ('current_site', models.CharField(blank=True, max_length=190, verbose_name='Текущий сайт')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='ID')),
                ('quantity_words', models.IntegerField(blank=True, null=True, verbose_name='Последнее количество найденных плохих слов')),
                ('is_parsed_data', models.BooleanField(default=False, verbose_name='Пропарсил плохие слова')),
                ('was_gotten_new_domain', models.BooleanField(default=False, max_length=190, verbose_name='Последний сайт')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'liked_users',
            },
        ),
    ]
