# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='words',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
