# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20171128_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Созданна')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Последнее редактирование')),
                ('domain_name', models.CharField(max_length=250, verbose_name='Доменное имя')),
            ],
            options={
                'verbose_name': 'Доменное имя',
                'verbose_name_plural': 'Доменные имена',
                'db_table': 'restricted_domains',
            },
        ),
        migrations.RenameField(
            model_name='word',
            old_name='name',
            new_name='word_name',
        ),
        migrations.AddField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_domains',
            field=models.ManyToManyField(blank=True, related_name='user_allowed_domains', to='words.UserDomain', verbose_name='Доменные имена'),
        ),
    ]
