# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20171124_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default=None, max_length=140, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=190, verbose_name='Email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрировался')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('words', models.ManyToManyField(blank=True, related_name='words', to='words.Word', verbose_name='Слова')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'liked_users',
            },
        ),
    ]
