# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20180112_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_quantity_words',
            field=models.IntegerField(default=15, verbose_name='Ограничение количество добавленных слов'),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Баланс пользователя'),
        ),
    ]
