# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_site',
            field=models.CharField(blank=True, max_length=190, verbose_name='Текущий сайт'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_site',
            field=models.CharField(blank=True, max_length=190, null=True, verbose_name='Последний сайт'),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=190, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=140, unique=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='words',
            field=models.ManyToManyField(blank=True, null=True, related_name='words', to='words.Word', verbose_name='Слова'),
        ),
    ]
