# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20180112_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temporary_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Временный код для восстановления пароля'),
        ),
    ]
