# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_auto_20171125_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quantity_words',
            field=models.IntegerField(blank=True, null=True, verbose_name='Последний сайт'),
        ),
    ]
