# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_user_quantity_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_parsed_data',
            field=models.BooleanField(default=False, verbose_name='Пропарсил плохие слова'),
        ),
        migrations.AlterField(
            model_name='user',
            name='quantity_words',
            field=models.IntegerField(blank=True, null=True, verbose_name='Последнее количество найденных плохих слов'),
        ),
    ]
