# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_auto_20171125_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_site',
        ),
        migrations.AddField(
            model_name='user',
            name='was_gotten_new_domain',
            field=models.BooleanField(default=False, max_length=190, verbose_name='Последний сайт'),
        ),
    ]
