# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать альбом?')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='albums', verbose_name='Изображение')),
                ('alt', models.CharField(default=uuid.uuid4, max_length=255, verbose_name='Альтернативный текст изображения')),
                ('width', models.IntegerField(default=0, help_text='По умолчанию - адаптивно', verbose_name='Ширина')),
                ('height', models.IntegerField(default=0, help_text='По умолчанию - адаптивно', verbose_name='Высонта')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=70)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.Album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
